name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v2
      with:
        files: coverage.txt
      
    - name: Install wkthtmltopdf
      run: |
        sudo apt-get install -y xfonts-base xfonts-75dpi
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .
