name: Ubuntu build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get install -y xfonts-base xfonts-75dpi
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: stable

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: TestPDFs
        path: '**/*.pdf'

    - name: CodeCov
      uses: codecov/codecov-action@v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.txt
